# Generated by Django 4.2.11 on 2024-04-18 09:11

from django.db import migrations, models
import ticket.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[ticket.validators.validate_iranian_phone_number])),
                ('description', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1)),
            ],
        ),
    ]
