# Generated by Django 4.2.11 on 2024-04-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='TicketModel',
        ),
    ]
