# Generated by Django 4.2.11 on 2024-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
