# Generated by Django 4.2.11 on 2024-04-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticketmodel_created_date_ticketmodel_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
