# Generated by Django 4.2.11 on 2024-06-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticketmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscribermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
