version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    restart: always

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
    env_file:
      - ./envs/dev/django/.env
    restart: always
    depends_on:
      - db

  mailhog:
    container_name: 'mailhog'
    image: mailhog/mailhog:v1.0.1
    volumes:
      - mailhog-data:/mail
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: always

volumes:
  mailhog-data:
