# Generated by Django 4.2.11 on 2024-04-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productmodel_brief_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagemodel',
            old_name='proudct',
            new_name='product',
        ),
    ]
