# Generated by Django 4.2.11 on 2024-05-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wishlistproductmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistproductmodel',
            options={'ordering': ('-id',)},
        ),
    ]
