# Generated by Django 4.2.11 on 2024-05-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_wishlistproductmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='average_rate',
            field=models.FloatField(default=0),
        ),
    ]
