# Generated by Django 4.2.11 on 2024-06-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_featuredproductmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproductmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel', unique=True),
        ),
    ]
