# Generated by Django 4.2.11 on 2024-06-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_featuredproductmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproductmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel'),
        ),
    ]
