# Generated by Django 4.2.11 on 2024-04-18 11:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponmodel',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('9999999999'), max_digits=10),
        ),
    ]
