# Generated by Django 4.2.11 on 2024-04-19 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cuponmodel_max_discount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddressmodel',
            options={'ordering': ('-updated_date',)},
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='کد پستی باید ده رقمی باشد')]),
        ),
    ]
