# Generated by Django 4.2.11 on 2024-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_useraddressmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponmodel',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
