# Generated by Django 4.2.11 on 2024-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_cuponmodel_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponmodel',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
