# Generated by Django 4.2.11 on 2024-04-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cuponmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponmodel',
            name='code',
            field=models.CharField(error_messages={'unique': 'تخفیفی با این کد قبلا ساخته شده است'}, max_length=100, unique=True),
        ),
    ]
