# Generated by Django 4.2.11 on 2024-05-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cuponmodel_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
    ]
