# Generated by Django 4.2.11 on 2024-05-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0007_alter_cuponmodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(choices=[(1, 'زرین پال')])),
                ('authority_id', models.CharField(max_length=124)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'پرداخت موفق'), (3, 'پرداخت ناموفق')], default=1)),
                ('ref_id', models.IntegerField()),
                ('response_code', models.IntegerField()),
                ('response_json', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order.ordermodel')),
            ],
        ),
    ]
