# Generated by Django 4.2.11 on 2024-05-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
