# Generated by Django 4.2.11 on 2024-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_response_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='response_json',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
    ]
