# Generated by Django 4.2.11 on 2024-05-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_response_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='response_json',
            field=models.JSONField(default=dict),
        ),
    ]
