# Generated by Django 4.2.11 on 2024-05-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cuponmodel_code'),
        ('payment', '0005_alter_payment_response_json'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentModel',
        )
    ]
