# Generated by Django 4.2.11 on 2024-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paymentmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='client',
            field=models.IntegerField(choices=[(1, 'زرین پال'), (2, 'آقای پرداخت'), (3, 'پی پینگ')]),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='ref_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
