# Generated by Django 4.2.11 on 2024-05-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproductmodel',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
